PL/ViewModels/EditRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PL.ViewModels
{
    public class EditRoleViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public DateTime? LockoutEndDateUtc { get; set; }
        public IList<string> UserRoles { get; set; }
        public List<string> AllRoles { get; set; }

        [Required]
        public List<string> EditedRoles { get; set; }

        [Display(Name = "Nickname")]
        public string NickName { get; set; }
    }
}

PL/Controllers/AdministratorController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using PL.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PL.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdministratorController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;

        /// <summary>
        /// Injects dependencies of IUserService and IMapper implementation
        /// </summary>
        /// <param name="userService">Reference to the IUserService interface</param>
        /// <param name="mapper">Reference to the IMapper interface</param>
        public AdministratorController(IUserService userService, IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="IEnumerable{}"/> of <see cref="EditRoleViewModel"/> model.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view.</returns>
        public ActionResult Users()
        {
            IEnumerable<EditRoleViewModel> model = _mapper.Map<IEnumerable<EditRoleViewModel>>(_userService.GetAll());
            return View(model);
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="EditRoleViewModel"/> model.
        /// </summary>
        /// <param name="id">User id</param>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        public async Task<ActionResult> EditRoles(string id)
        {
            EditRoleViewModel model = _mapper.Map<EditRoleViewModel>(await _userService.GetUserWithRolesByIdAsync(id));
            return View(model);
        }

        /// <summary>
        /// Processes the POST request to update user roles from <see cref="EditedRoles"/> field and returns view if it empty or redirects to EditRoles GET request.
        /// </summary>
        /// <param name="model"><see cref="EditRoleViewModel"/> model.</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditRoles(EditRoleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "There must be at least one role for user");
                return View(model);
            }
            await _userService.UpdateUserRolesAsync(model.Id, model.EditedRoles);

            return RedirectToAction("EditRoles", new { id = model.Id });
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="UserDto"/> model.
        /// </summary>
        /// <param name="id">User id</param>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        public async Task<ActionResult> Lock(string id)
        {
            UserDto model = await _userService.GetUserEmailByIdAsync(id);

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to lock user account
        /// </summary>
        /// <param name="id">User id</param>
        /// <returns><see cref="RedirectToRouteResult"/> to <see cref="Users"/> action.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Lock")]
        public async Task<ActionResult> LockConfirm(string id)
        {
            await _userService.LockUserByIdAsync(id);

            return RedirectToAction("Users");
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="UserDto"/> model.
        /// </summary>
        /// <param name="id">User id</param>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        public async Task<ActionResult> Unlock(string id)
        {
            UserDto model = await _userService.GetUserEmailByIdAsync(id);

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to unlock user account
        /// </summary>
        /// <param name="id">User id</param>
        /// <returns><see cref="RedirectToRouteResult"/> to <see cref="Users"/> action.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Unlock")]
        public async Task<ActionResult> UnlockConfirm(string id)
        {
            await _userService.UnlockUserByIdAsync(id);

            return RedirectToAction("Users");
        }
    }
}

PL/Controllers/PublicProfilesController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using Microsoft.AspNet.Identity;
using PL.Enums;
using PL.Models;
using PL.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PL.Controllers
{
    [Authorize]
    public class PublicProfilesController : Controller
    {
        private readonly IUserService _userService;
        private readonly IFilterService _filterService;
        private readonly IMapper _mapper;

        /// <summary>
        /// Injects dependencies of service implementations
        /// </summary>
        /// <param name="userService">Reference to the IUserService interface</param>
        /// <param name="filterService">Reference to the IFilterService interface</param>
        /// <param name="mapper">Reference to the IMapper interface</param>
        public PublicProfilesController(IUserService userService, IFilterService filterService, IMapper mapper)
        {
            _userService = userService;
            _filterService = filterService;
            _mapper = mapper;
        }

        /// <summary>
        /// Processes the GET request and returns public profile of user.
        /// </summary>
        /// <param name="id">User id</param>
        /// <returns><see cref="ViewResult"/> view with <see cref="PublicProfileViewModel"/> model.</returns>
        [HttpGet]
        public new async Task<ActionResult> Profile(string id)
        {
            var publicProfileViewModel = _mapper.Map<PublicProfileViewModel>(await _userService.GetUserProfileByIdAsync(id));
            return View(publicProfileViewModel);
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="PublicProfileViewModel"/> model.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        public async Task<ActionResult> Update()
        {
            string userId = User.Identity.GetUserId();
            var publicProfileViewModel = _mapper.Map<PublicProfileViewModel>(await _userService.GetUserProfileByIdAsync(userId));
            return View(publicProfileViewModel);
        }

        /// <summary>
        /// Processes the POST request to update public profile.
        /// </summary>
        /// <param name="model"><see cref="PublicProfileViewModel"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(PublicProfileViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var userProfile = _mapper.Map<PublicProfileViewModel>(await _userService.GetUserProfileByIdAsync(userId));
                return View(userProfile);
            }

            var editedUserProfile = _mapper.Map<UserDto>(model);
            editedUserProfile.Id = User.Identity.GetUserId();
            await _userService.UpdateProfileAsync(editedUserProfile);

            return RedirectToAction("Update");
        }

        /// <summary>
        /// Processes the GET request to return view with user filter.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view with <see cref="UserFilterViewModel"/> model.</returns>
        [HttpGet]
        [Authorize(Roles = "Manager")]
        public ActionResult Filter()
        {
            UserFilterViewModel model = new UserFilterViewModel();
            model.Filters = new PublicProfileFiltersViewModel();
            model.Filters.AllTags = _filterService.GetAllTechnologyTagNames();
            model.Filters.EnglishLevels = new List<EnglishLevelModel>();
            foreach (EnglishLevel value in Enum.GetValues(typeof(EnglishLevel)))
            {
                model.Filters.EnglishLevels.Add(new EnglishLevelModel() { EnglishLevel = value, IsSelected = false });
            }

            model.UserPublicProfiles = _mapper.Map<IEnumerable<PublicProfileViewModel>>(_userService.GetUserProfilesWithEmail());

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to return the list of users according to the filter.
        /// </summary>
        /// <param name="model"></param>
        /// <returns><see cref="ViewResult"/> view with <see cref="UserFilterViewModel"/> model.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public ActionResult Filter(UserFilterViewModel model)
        {
            List<string> technologyTags = model.Filters.SelectedTags;
            List<string> englishLevels = model.Filters.EnglishLevels
                .Where(x => x.IsSelected)
                .Select(x => x.EnglishLevel.ToString())
                .ToList();

            model.UserPublicProfiles = _mapper.Map<IEnumerable<PublicProfileViewModel>>(_filterService.GetUsersByFilter(englishLevels, technologyTags));
            model.Filters.AllTags = _filterService.GetAllTechnologyTagNames();

            return View(model);
        }
    }
}

PL/Views/Administrator/EditRoles.cshtml
@model PL.ViewModels.EditRoleViewModel

@{
    ViewBag.Title = "Edit roles for " + Model.Email;
}

<h2>Select roles for user @Model.Email</h2>

@using (Html.BeginForm("EditRoles", "Administrator", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Email)
    for (int i = 0; i < Model.AllRoles.Count; i++)
    {
        @Html.HiddenFor(model => model.AllRoles[i])
    }
    for (int i = 0; i < Model.UserRoles.Count; i++)
    {
        @Html.HiddenFor(model => model.UserRoles[i])
    }

    <div class="form-group">
        @foreach (var role in Model.AllRoles)
        {
            <input type="checkbox" name="EditedRoles" value="@role"
                   @(Model.UserRoles.Contains(role) ? "checked=\"checked\"" : "") /> @role<br />
            }
    </div>
    <input type="submit" value="Submit" class="btn btn-success" />
}

PL/Views/Administrator/Lock.cshtml
@model BLL.DTO.UserDto

@{
    ViewBag.Title = "Lock confirmation";
}

<h3>Are you sure you want to lock @Html.ActionLink(Model.Email, "Profile", "PublicProfiles", new { id = Model.Id }, new { }) user?</h3>

<div>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Lock" class="btn btn-danger" />
        </div>
    }
</div>

PL/Views/Administrator/Unlock.cshtml
@model BLL.DTO.UserDto

@{
    ViewBag.Title = "Unlock confirmation";
}

<h3>Unlock @Html.ActionLink(Model.Email, "Profile", "PublicProfiles", new { id = Model.Id }, new { }) user?</h3>

<div>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Unlock" class="btn btn-success" />
        </div>
    }
</div>

PL/Views/Administrator/Users.cshtml
@model IEnumerable<PL.ViewModels.EditRoleViewModel>

@{
    ViewBag.Title = "User manager";
}

<h2 class="text-center">All registered users:</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NickName)
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink(item.NickName, "Profile", "PublicProfiles", new { id = item.Id }, new { })
        </td>
        <td>
            @Html.ActionLink("Roles", "EditRoles", new { id = item.Id }) | 
            @if (item.LockoutEndDateUtc == null)
            {
                @Html.ActionLink("Lock", "Lock", new { id = item.Id })
            }
            else
            {
                @Html.ActionLink("Unlock", "Unlock", new { id = item.Id })
            }
        </td>
    </tr>
}
</table>