PL/Controllers/ArticlesController.cs
using BLL.DTO;
using BLL.Interfaces;
using PagedList;
using PL.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IArticleTagService _articleTagService;
        private readonly ICategoryService _categoryService;
        private readonly IFilterService _filterService;

        /// <summary>
        /// Injects dependencies of service implementations
        /// </summary>
        /// <param name="articleService">Reference to the IArticleService interface</param>
        /// <param name="articleTagService">Reference to the IArticleTagService interface</param>
        /// <param name="categoryService">Reference to the ICategoryService interface</param>
        /// <param name="filterService">Reference to the IFilterService interface</param>
        public ArticlesController(IArticleService articleService, IArticleTagService articleTagService, ICategoryService categoryService, IFilterService filterService)
        {
            _articleService = articleService;
            _articleTagService = articleTagService;
            _categoryService = categoryService;
            _filterService = filterService;
        }

        /// <summary>
        /// Processes the GET request and returns all articles ordered by date descending. 
        /// </summary>
        /// <param name="page">Number of current page</param>
        /// <returns><see cref="ViewResult"/> view with paged list of <see cref="ArticleDto"/>.</returns>
        public ActionResult Recent(int? page)
        {
            IEnumerable<ArticleDto> model = _articleService.GetAll();
            int pageSize = 5;
            int pageNumber = page ?? 1;
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Processes the POST request and returns all categories.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view.</returns>
        public ActionResult Categories()
        {
            IEnumerable<CategoryDto> model = _categoryService.GetAll();
            return View(model);
        }

        /// <summary>
        /// Processes the GET request and returns all articles in certain category, ordered by date descending. 
        /// </summary>
        /// <param name="id">Category id</param>
        /// <param name="page">Number of current page</param>
        /// <returns><see cref="ViewResult"/> view with paged list of <see cref="ArticleDto"/>.</returns>
        public async Task<ActionResult> Category(int id, int? page)
        {
            IEnumerable<ArticleDto> model = await _filterService.GetArticlesWithDetailsByCategoryIdAsync(id);
            ViewBag.Category = await _categoryService.GetByIdAsync(id);
            int pageSize = 5;
            int pageNumber = page ?? 1;
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Processes the GET request and returns all articles with certain tag, ordered by date descending. 
        /// </summary>
        /// <param name="id">Category id</param>
        /// <param name="page">Number of current page</param>
        /// <returns><see cref="ViewResult"/> view with paged list of <see cref="ArticleDto"/>.</returns>
        public async Task<ActionResult> Tag(int id, int? page)
        {
            int pageSize = 5;
            int pageNumber = page ?? 1;
            IEnumerable<ArticleDto> model = await _filterService.GetArticlesWithDetailsByTagIdAsync(id);
            ViewBag.Tag = await _articleTagService.GetByIdAsync(id);
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Processes the GET request and returns view with full version of article.
        /// </summary>
        /// <param name="id">Category id</param>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticlePageViewModel"/> model.</returns>
        public async Task<ActionResult> Article(int id)
        {
            ArticlePageViewModel model = new ArticlePageViewModel();
            model.Article = await _articleService.GetByIdAsync(id);
            model.Comment = new CommentDto();
            return View(model);
        }

        /// <summary>
        /// Processes the GET request and returns view with empty <see cref="ArticleDto"/> model.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticleDto"/> model.</returns>
        [HttpGet]
        [Authorize(Roles = "Writer")]
        public ActionResult Add()
        {
            var model = new ArticleDto
            {
                AllTags = _articleTagService.GetAll().ToList(),
                AllCategories = _categoryService.GetAll().ToList()
            };
            return View(model);
        }

        /// <summary>
        /// Processes the POST request to add a new article.
        /// </summary>
        /// <param name="model"><see cref="ArticleDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Writer")]
        public async Task<ActionResult> Add(ArticleDto model)
        {
            if (!ModelState.IsValid)
            {
                model.AllTags = _articleTagService.GetAll().ToList();
                model.AllCategories = _categoryService.GetAll().ToList();
                return View(model);
            }

            await _articleService.AddAsync(model);

            return RedirectToAction("Recent");
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="ArticleDto"/> model.
        /// </summary>
        /// <param name="id">Article id</param>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticleDto"/> model.</returns>
        [HttpGet]
        [Authorize(Roles = "Writer")]
        public async Task<ActionResult> Update(int id)
        {
            ArticleDto model = await _articleService.GetByIdAsync(id);
            model.AllTags = _articleTagService.GetAll().ToList();
            model.AllCategories = _categoryService.GetAll().ToList();

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to update tag.
        /// </summary>
        /// <param name="model"><see cref="ArticleTagDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Writer")]
        public async Task<ActionResult> Update(ArticleDto model)
        {
            if (!ModelState.IsValid)
            {
                model.ArticleTags = await _articleTagService.GetTagsByArticleIdAsync(model.Id);
                model.AllTags = _articleTagService.GetAll().ToList();
                model.AllCategories = _categoryService.GetAll().ToList();
                return View(model);
            }

            await _articleService.UpdateAsync(model);

            return RedirectToAction("Article", new { id = model.Id });
        }

        /// <summary>
        /// Processes the GET request to delete article confirmation.
        /// </summary>
        /// <param name="id">Tag id</param>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticleDto"/> model.</returns>
        [HttpGet]
        [Authorize(Roles = "Writer")]
        public async Task<ActionResult> Delete(int id)
        {
            ArticleDto model = await _articleService.GetByIdAsync(id);

            return View(model);
        }

        /// <summary>
        /// Processes the GET request to delete article.
        /// </summary>
        /// <param name="id">Article id</param>
        /// <returns><see cref="RedirectToRouteResult"/> view.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Writer")]
        [ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            await _articleService.DeleteByIdAsync(id);

            return RedirectToAction("Recent");
        }

        /// <summary>
        /// Processes the GET request and returns view with random article. 
        /// </summary>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticleDto"/> model.</returns>
        public async Task<ActionResult> RandomArticle()
        {
            ArticlePageViewModel model = new ArticlePageViewModel();
            model.Comment = new CommentDto();
            model.Article = await _articleService.GetRandomArticleAsync();
            model.Comment = new CommentDto();
            return View("Article", model);
        }
    }
}

PL/Controllers/CommentsController.cs
using BLL.DTO;
using BLL.Interfaces;
using Microsoft.AspNet.Identity;
using PL.ViewModels;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentService _commentService;
        private readonly IArticleService _articleService;

        /// <summary>
        /// Injects dependencies of service implementations
        /// </summary>
        /// <param name="commentService">Reference to the ICommentService interface</param>
        /// <param name="articleService">Reference to the IArticleService interface</param>
        public CommentsController(ICommentService commentService, IArticleService articleService)
        {
            _commentService = commentService;
            _articleService = articleService;
        }

        /// <summary>
        /// Processes the POST request to add a new comment.
        /// </summary>
        /// <param name="model"><see cref="ArticlePageViewModel"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(ArticlePageViewModel model)
        {
            var validationResults = new List<ValidationResult>();
            var validationContext = new ValidationContext(model.Comment);
            if (!Validator.TryValidateObject(model.Comment, validationContext, validationResults, true))
            {
                model.Article = await _articleService.GetByIdAsync(model.Article.Id);
                return View("Article", model);
            }

            model.Comment.UserId = User.Identity.GetUserId();
            model.Comment.ArticleId = model.Article.Id;

            await _commentService.AddAsync(model.Comment);

            return RedirectToAction("Article", "Articles", new { id = model.Article.Id });
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="CommentDto"/> model.
        /// </summary>
        /// <param name="id">Comment id</param>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        public async Task<ActionResult> Update(int id)
        {
            CommentDto model = await _commentService.GetByIdAsync(id);

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to update comment.
        /// </summary>
        /// <param name="model"><see cref="CommentDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(CommentDto model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await _commentService.UpdateAsync(model);

            return RedirectToAction("Article", "Articles", new { id = model.ArticleId });
        }

        /// <summary>
        /// Processes the GET request to delete comment confirmation.
        /// </summary>
        /// <param name="id">Comment id</param>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            CommentDto model = await _commentService.GetByIdAsync(id);

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to delete comment.
        /// </summary>
        /// <param name="model"><see cref="CommentDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirm(CommentDto model)
        {
            await _commentService.DeleteByIdAsync(model.Id);

            return RedirectToAction("Article", "Articles", new { id = model.ArticleId });
        }
    }
}

PL/Views/Articles/Add.cshtml
@model BLL.DTO.ArticleDto

@{
    ViewBag.Title = "New article";
}

<h2>Create article</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, new { @class = "form-control", @rows = "40", @style = "resize: none;" })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                <p>You can use &lt;b&gt;&lt;/b&gt;, &lt;i&gt;&lt;/i&gt; and &lt;code&gt;&lt;/code&gt; html tags.</p>
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.AllCategories, "Id", "Name"))
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.ArticleTags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @foreach (var tag in Model.AllTags)
                {
                    <input type="checkbox" name="EditedTagIds" value="@tag.Id"
                           @(Model.ArticleTags.Contains(tag) ? "checked=\"checked\"" : "") /> @tag.Name<br>
                }
                @Html.ValidationMessageFor(model => model.EditedTagIds, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group text-center">
            <input type="submit" value="Create article" class="btn btn-default" />
        </div>
    </div>
}

PL/Views/Articles/Article.cshtml
@model PL.ViewModels.ArticlePageViewModel

@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = Model.Article.Name;
}

@if (User.IsInRole("Writer"))
{
    <a href="@Url.Action("Update", new { id = Model.Article.Id })" style="margin-right:20px"><img alt="Edit" src="~/Content/Icons/edit.png"></a>
    <a href="@Url.Action("Delete", new { id = Model.Article.Id })"><img alt="Delete" src="~/Content/Icons/delete.png"></a>
}

<h2>@Model.Article.Name</h2>
<h5><span class="glyphicon glyphicon-time"></span> Last change: @Model.Article.LastChangeDate.ToShortDateString()</h5>
<h5>
    @{
        foreach (var tag in Model.Article.ArticleTags)
        {
            <a href="@Url.Action("Tag", new { id = tag.Id })"><span class="label label-primary">@tag.Name</span></a>
        }
    }
</h5>

<div class="text-break">
    @Html.Raw(Model.Article.Text.Replace(Environment.NewLine, "<br/>"))
</div>

<h5><span class="glyphicon glyphicon-time"></span> Posted: @Model.Article.PostDate.ToShortDateString()</h5>
<hr>
<p>Comments: <span class="badge">@Model.Article.Comments.Count()</span></p>
<br>

@if (User.Identity.IsAuthenticated)
{
    <h4>Leave a Comment:</h4>
    using (Html.BeginForm("Add", "Comments", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(x => x.Article.Id)

        <div class="form-group">
            @Html.TextAreaFor(model => model.Comment.Text, new { @class = "form-control", @rows = "5", @style = "resize: none;" })
            @Html.ValidationMessageFor(model => model.Comment.Text, "", new { @class = "text-danger" })
        </div>
        <input type="submit" value="Submit" class="btn btn-success" />
    }
}
else
{
    <p>Please, <a href="@Url.Action("SignIn", "Account")">Sign In</a>, to leave a comment.</p>
}

<br>
<br>

<div class="row">
    @foreach (var comment in Model.Article.Comments)
    {
    <div class="col-sm-11">
        <div class="row">
            <h4>
                <div class="col-md-6">
                    @Html.ActionLink(comment.NickName, "Profile", "PublicProfiles", new { id = comment.UserId }, new { })
                    <small>@comment.PostDate.ToShortDateString() @comment.PostDate.ToShortTimeString()</small>
                </div>
                <div class="col-md-6 text-right">
                    <small>
                        @if (User.Identity.GetUserId() == comment.UserId)
                        {
                            @Html.ActionLink("Edit", "Update", "Comments", new { id = comment.Id }, new { })
                            <span> | </span>
                        }
                        @if (User.IsInRole("Administrator") || User.Identity.GetUserId() == comment.UserId)
                        {
                            @Html.ActionLink("Delete", "Delete", "Comments", new { id = comment.Id }, new { })
                        }
                    </small>
                </div>
            </h4>
        </div>
        <p>@comment.Text</p>
        <br>
    </div>
    }
</div>

<br>
<br>

PL/Views/Articles/Categories.cshtml
@model IEnumerable<BLL.DTO.CategoryDto>

@{
    ViewBag.Title = "Categories";
}

@{
    if (Model.Any())
    {
        foreach (var category in Model)
        {
            <div class="col-md-4">
                <h2>@category.Name</h2>
                <div class="text-break">
                    <p>@category.Description</p>
                </div>
                <p><a class="btn btn-default" href="@Url.Action("Category", "Articles", new { id = category.Id })" role="button">View articles &raquo;</a></p>
            </div>
        }
    }
    else
    {
        <p class="text-center">There are no categories now...</p>
    }
}

PL/Views/Articles/Category.cshtml
@model PagedList.IPagedList<BLL.DTO.ArticleDto>

@using PagedList.Mvc;

@{
    ViewBag.Title = ViewBag.Category.Name + " articles";
}

@{
    if (Model.Any())
    {
        foreach (var article in Model)
        {
            <a href="@Url.Action("Article", new { id = article.Id })"><h2>@article.Name</h2></a>
            <h5><span class="glyphicon glyphicon-time"></span> Last change: @article.LastChangeDate.ToShortDateString()</h5>
            <h5>
                @{
                    foreach (var tag in article.ArticleTags)
                    {
                        <a href="@Url.Action("Tag", new { id = tag.Id })"><span class="label label-primary">@tag.Name</span></a>
                    }
                }
            </h5>

            string shortArticle = "";
            if (article.Text.Length > 400)
            {
                shortArticle = new string(article.Text.Take(400).ToArray());
                shortArticle += " ...";
            }
            else
            {
                shortArticle = article.Text;
            }

            <div class="text-break">
                @shortArticle
            </div>

            <h5><span class="glyphicon glyphicon-time"></span> Posted: @article.PostDate.ToShortDateString()</h5>
            <hr>
            <p>Comments: <span class="badge"> @article.Comments.Count()</span></p>
            <br>
        }
    }
    else
    {
        <h4 class="text-center">This category currently has no articles, come back later...</h4>
    }
}

<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("Category", new { ViewBag.Category.Id, page }))
</div>

PL/Views/Articles/Delete.cshtml
@model BLL.DTO.ArticleDto

@{
    ViewBag.Title = "Article delete confirmation";
}

<h2>Delete selected article</h2>

<h3>Are you sure you want to delete this article?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastChangeDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastChangeDate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to full version", "Article", new { id = Model.Id })
        </div>
    }
</div>

PL/Views/Articles/Recent.cshtml
@model PagedList.IPagedList<BLL.DTO.ArticleDto>

@using PagedList.Mvc;

@{
    ViewBag.Title = "Recent articles";
}

@{
    foreach (var article in Model)
    {
        <a href="@Url.Action("Article", new { id = article.Id })"><h2>@article.Name</h2></a>
        <h5><span class="glyphicon glyphicon-time"></span> Last change: @article.LastChangeDate.ToShortDateString()</h5>
        <h5>
            @{
                foreach (var tag in article.ArticleTags)
                {
                    <a href="@Url.Action("Tag", new { id = tag.Id })"><span class="label label-primary">@tag.Name</span></a>
                }
            }
        </h5>

        string shortArticle = "";
        if (article.Text.Length > 400)
        {
            shortArticle = new string(article.Text.Take(400).ToArray());
            shortArticle += " ...";
        }
        else
        {
            shortArticle = article.Text;
        }

        <div class="text-break">
            @shortArticle
        </div>

        <h5><span class="glyphicon glyphicon-time"></span> Posted: @article.PostDate.ToShortDateString()</h5>
        <hr>
        <p>Comments: <span class="badge">@article.Comments.Count()</span></p>
        <br>
    }
}

<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("Recent", new { page }))
</div>

PL/Views/Articles/Tag.cshtml
@model PagedList.IPagedList<BLL.DTO.ArticleDto>

@using PagedList.Mvc;

@{
    ViewBag.Title = ViewBag.Tag.Name + " tag";
}

@{
    if (Model.Any())
    {
        foreach (var article in Model)
        {
            <a href="@Url.Action("Article", new { id = article.Id })"><h2>@article.Name</h2></a>
            <h5><span class="glyphicon glyphicon-time"></span> Last change: @article.LastChangeDate.ToShortDateString()</h5>
            <h5>
                @{
                    foreach (var tag in article.ArticleTags)
                    {
                        <a href="@Url.Action("Tag", new { id = tag.Id })"><span class="label label-primary">@tag.Name</span></a>
                    }
                }
            </h5>

            string shortArticle = "";
            if (article.Text.Length > 200)
            {
                shortArticle = new string(article.Text.Take(200).ToArray());
                shortArticle += " ...";
            }
            else
            {
                shortArticle = article.Text;
            }

            @shortArticle

            <h5><span class="glyphicon glyphicon-time"></span> Posted: @article.PostDate.ToShortDateString()</h5>
            <hr>
            <p>Comments: <span class="badge"> @article.Comments.Count()</span></p>
            <br>
        }
    }
    else
    {
        <p class="text-center">This category is currently being filled, come back later...</p>
    }
}

<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("Tag", new { ViewBag.Tag.Id, page }))
</div>

PL/Views/Articles/Update.cshtml
@model BLL.DTO.ArticleDto

@{
    ViewBag.Title = "Edit article";
}

<h2>Edit selected article</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Text, new { @class = "form-control", @rows = "40", @style = "resize: none;" })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            <p>You can use &lt;b&gt;&lt;/b&gt;, &lt;i&gt;&lt;/i&gt; and &lt;code&gt;&lt;/code&gt; html tags.</p>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.AllCategories, "Id", "Name", Model.CategoryId))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ArticleTags, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @foreach (var tag in Model.AllTags)
            {
                <input type="checkbox" name="EditedTagIds" value="@tag.Id"
                       @(Model.ArticleTags.Select(x => x.Id).Contains(tag.Id) ? "checked=\"checked\"" : "") /> @tag.Name<br>
                }
            @Html.ValidationMessageFor(model => model.EditedTagIds, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(x => x.PostDate)

    <div class="form-group text-center">
        <input type="submit" value="Save" class="btn btn-success" />
    </div>
</div>
}