PL/Controllers/ArticleTagsController.cs
using BLL.DTO;
using BLL.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PL.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ArticleTagsController : Controller
    {
        private readonly IArticleTagService _articleTagService;

        /// <summary>
        /// Injects dependencies of IArticleTagService implementation
        /// </summary>
        /// <param name="articleTagService">Reference to the IArticleTagService interface</param>
        public ArticleTagsController(IArticleTagService articleTagService)
        {
            _articleTagService = articleTagService;
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="IEnumerable{}" /> of <see cref="ArticleTagDto"/> model.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view.</returns>
        public ActionResult List()
        {
            IEnumerable<ArticleTagDto> articleTags = _articleTagService.GetAll();
            return View(articleTags);
        }

        /// <summary>
        /// Processes the GET request and returns view.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Processes the POST request to add a new tag.
        /// </summary>
        /// <param name="model"><see cref="ArticleTagDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(ArticleTagDto model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await _articleTagService.AddAsync(model);

            return RedirectToAction("List");
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="ArticleTagDto"/> model.
        /// </summary>
        /// <param name="id">Tag id</param>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        public async Task<ActionResult> Update(int id)
        {
            ArticleTagDto model = await _articleTagService.GetByIdAsync(id);

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to update tag.
        /// </summary>
        /// <param name="model"><see cref="ArticleTagDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(ArticleTagDto model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await _articleTagService.UpdateAsync(model);

            return RedirectToAction("List");
        }

        /// <summary>
        /// Processes the GET request to delete tag confirmation.
        /// </summary>
        /// <param name="id">Tag id</param>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            ArticleTagDto model = await _articleTagService.GetByIdAsync(id);

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to delete tag.
        /// </summary>
        /// <param name="model"><see cref="ArticleTagDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            await _articleTagService.DeleteByIdAsync(id);

            return RedirectToAction("List");
        }
    }
}

PL/Controllers/ArticlesController.cs
using BLL.DTO;
using BLL.Interfaces;
using PagedList;
using PL.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IArticleTagService _articleTagService;
        private readonly ICategoryService _categoryService;
        private readonly IFilterService _filterService;

        /// <summary>
        /// Injects dependencies of service implementations
        /// </summary>
        /// <param name="articleService">Reference to the IArticleService interface</param>
        /// <param name="articleTagService">Reference to the IArticleTagService interface</param>
        /// <param name="categoryService">Reference to the ICategoryService interface</param>
        /// <param name="filterService">Reference to the IFilterService interface</param>
        public ArticlesController(IArticleService articleService, IArticleTagService articleTagService, ICategoryService categoryService, IFilterService filterService)
        {
            _articleService = articleService;
            _articleTagService = articleTagService;
            _categoryService = categoryService;
            _filterService = filterService;
        }

        /// <summary>
        /// Processes the GET request and returns all articles ordered by date descending. 
        /// </summary>
        /// <param name="page">Number of current page</param>
        /// <returns><see cref="ViewResult"/> view with paged list of <see cref="ArticleDto"/>.</returns>
        public ActionResult Recent(int? page)
        {
            IEnumerable<ArticleDto> model = _articleService.GetAll();
            int pageSize = 5;
            int pageNumber = page ?? 1;
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Processes the POST request and returns all categories.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view.</returns>
        public ActionResult Categories()
        {
            IEnumerable<CategoryDto> model = _categoryService.GetAll();
            return View(model);
        }

        /// <summary>
        /// Processes the GET request and returns all articles in certain category, ordered by date descending. 
        /// </summary>
        /// <param name="id">Category id</param>
        /// <param name="page">Number of current page</param>
        /// <returns><see cref="ViewResult"/> view with paged list of <see cref="ArticleDto"/>.</returns>
        public async Task<ActionResult> Category(int id, int? page)
        {
            IEnumerable<ArticleDto> model = await _filterService.GetArticlesWithDetailsByCategoryIdAsync(id);
            ViewBag.Category = await _categoryService.GetByIdAsync(id);
            int pageSize = 5;
            int pageNumber = page ?? 1;
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Processes the GET request and returns all articles with certain tag, ordered by date descending. 
        /// </summary>
        /// <param name="id">Category id</param>
        /// <param name="page">Number of current page</param>
        /// <returns><see cref="ViewResult"/> view with paged list of <see cref="ArticleDto"/>.</returns>
        public async Task<ActionResult> Tag(int id, int? page)
        {
            int pageSize = 5;
            int pageNumber = page ?? 1;
            IEnumerable<ArticleDto> model = await _filterService.GetArticlesWithDetailsByTagIdAsync(id);
            ViewBag.Tag = await _articleTagService.GetByIdAsync(id);
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Processes the GET request and returns view with full version of article.
        /// </summary>
        /// <param name="id">Category id</param>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticlePageViewModel"/> model.</returns>
        public async Task<ActionResult> Article(int id)
        {
            ArticlePageViewModel model = new ArticlePageViewModel();
            model.Article = await _articleService.GetByIdAsync(id);
            model.Comment = new CommentDto();
            return View(model);
        }

        /// <summary>
        /// Processes the GET request and returns view with empty <see cref="ArticleDto"/> model.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticleDto"/> model.</returns>
        [HttpGet]
        [Authorize(Roles = "Writer")]
        public ActionResult Add()
        {
            var model = new ArticleDto
            {
                AllTags = _articleTagService.GetAll().ToList(),
                AllCategories = _categoryService.GetAll().ToList()
            };
            return View(model);
        }

        /// <summary>
        /// Processes the POST request to add a new article.
        /// </summary>
        /// <param name="model"><see cref="ArticleDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Writer")]
        public async Task<ActionResult> Add(ArticleDto model)
        {
            if (!ModelState.IsValid)
            {
                model.AllTags = _articleTagService.GetAll().ToList();
                model.AllCategories = _categoryService.GetAll().ToList();
                return View(model);
            }

            await _articleService.AddAsync(model);

            return RedirectToAction("Recent");
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="ArticleDto"/> model.
        /// </summary>
        /// <param name="id">Article id</param>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticleDto"/> model.</returns>
        [HttpGet]
        [Authorize(Roles = "Writer")]
        public async Task<ActionResult> Update(int id)
        {
            ArticleDto model = await _articleService.GetByIdAsync(id);
            model.AllTags = _articleTagService.GetAll().ToList();
            model.AllCategories = _categoryService.GetAll().ToList();

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to update tag.
        /// </summary>
        /// <param name="model"><see cref="ArticleTagDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Writer")]
        public async Task<ActionResult> Update(ArticleDto model)
        {
            if (!ModelState.IsValid)
            {
                model.ArticleTags = await _articleTagService.GetTagsByArticleIdAsync(model.Id);
                model.AllTags = _articleTagService.GetAll().ToList();
                model.AllCategories = _categoryService.GetAll().ToList();
                return View(model);
            }

            await _articleService.UpdateAsync(model);

            return RedirectToAction("Article", new { id = model.Id });
        }

        /// <summary>
        /// Processes the GET request to delete article confirmation.
        /// </summary>
        /// <param name="id">Tag id</param>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticleDto"/> model.</returns>
        [HttpGet]
        [Authorize(Roles = "Writer")]
        public async Task<ActionResult> Delete(int id)
        {
            ArticleDto model = await _articleService.GetByIdAsync(id);

            return View(model);
        }

        /// <summary>
        /// Processes the GET request to delete article.
        /// </summary>
        /// <param name="id">Article id</param>
        /// <returns><see cref="RedirectToRouteResult"/> view.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Writer")]
        [ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            await _articleService.DeleteByIdAsync(id);

            return RedirectToAction("Recent");
        }

        /// <summary>
        /// Processes the GET request and returns view with random article. 
        /// </summary>
        /// <returns><see cref="ViewResult"/> view with <see cref="ArticleDto"/> model.</returns>
        public async Task<ActionResult> RandomArticle()
        {
            ArticlePageViewModel model = new ArticlePageViewModel();
            model.Comment = new CommentDto();
            model.Article = await _articleService.GetRandomArticleAsync();
            model.Comment = new CommentDto();
            return View("Article", model);
        }
    }
}

PL/Controllers/ReportsController.cs
using BLL.DTO;
using BLL.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IReportService _reportService;

        /// <summary>
        /// Injects dependencies of IReportService implementation
        /// </summary>
        /// <param name="reportService">Reference to the IReportService interface</param>
        public ReportsController(IReportService reportService)
        {
            _reportService = reportService;
        }

        /// <summary>
        /// Processes the GET request and returns view with <see cref="IEnumerable{}" /> of <see cref="ReportDto"/> model.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [Authorize(Roles = "Administrator")]
        public ActionResult List()
        {
            IEnumerable<ReportDto> reports = _reportService.GetAll();
            return View(reports);
        }

        /// <summary>
        /// Processes the GET request and returns view.
        /// </summary>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        [Authorize]
        public ActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Processes the POST request to add a new report.
        /// </summary>
        /// <param name="model"><see cref="ReportDto"/> model</param>
        /// <returns><see cref="ActionResult"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(ReportDto model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            model.UserEmail = User.Identity.Name;
            await _reportService.AddAsync(model);

            return RedirectToAction("Confirmed");
        }


        [HttpGet]
        public ActionResult Confirmed()
        {
            return View();
        }

        /// <summary>
        /// Processes the GET request to delete report confirmation.
        /// </summary>
        /// <param name="id">Tag id</param>
        /// <returns><see cref="ViewResult"/> view.</returns>
        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Delete(int id)
        {
            ReportDto model = await _reportService.GetByIdAsync(id);

            return View(model);
        }

        /// <summary>
        /// Processes the POST request to delete report.
        /// </summary>
        /// <param name="model"><see cref="ReportDto"/> model</param>
        /// <returns><see cref="ReportDto"/> that can be <see cref="RedirectToRouteResult"/> or <see cref="ViewResult"/>.</returns>
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            await _reportService.DeleteByIdAsync(id);

            return RedirectToAction("List");
        }
    }
}

PL/Views/Shared/InternalError.cshtml
@{
    ViewBag.Title = "Internal Error";
}

<div class="text-center">
    <img src="~/Content/Icons/error.png" alt="Error image">
    <h1>Oops, something went wrong...</h1>
    <h2>An error occurred while processing your request.</h2>
    <p>Error code: @Response.StatusCode</p>
</div>

PL/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Page not found";
}

<div class="text-center">
    <img src="~/Content/Icons/error.png" alt="Error image">
    <h1>Page not found...</h1>
    <h2>We're sorry, we couldn't find the page you requested.</h2>
    <p>Error code: @Response.StatusCode</p>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Knowledge base</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img alt="Logo" class="navbar-brand" src="~/Content/Icons/programming.png">
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Recent articles", "Recent", "Articles")</li>
                    <li>@Html.ActionLink("Categories", "Categories", "Articles")</li>
                    <li>@Html.ActionLink("Random article", "RandomArticle", "Articles")</li>
                </ul>

                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </nav>

    <div class="container main">
        <div class="row content">

            <div class="col-sm-2 sidebar">
                <div class="list-group">
                    @Html.Partial("_MenuPartial")
                </div>
            </div>

            <div class="container">
                <div class="col-md-10 text-left">
                    @RenderBody()
                </div>
            </div>

        </div>
    </div>

    <footer class="container-fluid text-center">
        <p class="footer-text">
            &copy; Knowledge base | @DateTime.Now.Year | All rights reserved | Denis Fokin
            <br>Icons made by <a href="https://www.freepik.com" title="Freepik" style="color:skyblue">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon" style="color:skyblue">www.flaticon.com</a>
        </p>
    </footer>

    @Scripts.Render("~/Scripts/jquery")
    @Scripts.Render("~/Scripts/bootstrap")
</body>
</html>

PL/Views/Shared/_MenuPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("Public profile", "Update", "PublicProfiles", null, new { @class = "list-group-item" })
    @Html.ActionLink("Report a problem", "Add", "Reports", null, new { @class = "list-group-item" })
    if (User.IsInRole("Administrator"))
    {
        @Html.ActionLink("Manage users", "Users", "Administrator", null, new { @class = "list-group-item" })
        @Html.ActionLink("Manage categories", "List", "Categories", null, new { @class = "list-group-item" })
        @Html.ActionLink("Manage article tags", "List", "ArticleTags", null, new { @class = "list-group-item" })
        @Html.ActionLink("Manage technology tags", "List", "TechnologyTags", null, new { @class = "list-group-item" })
        @Html.ActionLink("Reports", "List", "Reports", null, new { @class = "list-group-item" })
    }
    if (User.IsInRole("Writer"))
    {
        @Html.ActionLink("New article", "Add", "Articles", null, new { @class = "list-group-item" })
    }
    if (User.IsInRole("Manager"))
    {
        @Html.ActionLink("User list", "Filter", "PublicProfiles", null, new { @class = "list-group-item" })
    }
}
else
{
    <p class="text-center">You can <a href="@Url.Action("SignIn", "Account")">Sign In</a> to get more possibilites!</p>
}